apiVersion: v1
kind: Service
metadata:
 name: brain-tasks-service
 annotations:
 service.beta.kubernetes.io/aws-load-balancer-type: "nlb"
 service.beta.kubernetes.io/aws-load-balancer-scheme: "internet-facing"
spec:
 selector:
 app: brain-tasks-app
 ports:
 - protocol: TCP
 port: 80
 targetPort: 3000
 type: LoadBalanc
